### ISSUE TITLE
PLN LDA can't plot when the grouping variable has only two levels

### ISSUE THREAD

**Issue by cpauvert** [jchiquet/PLNmodels#1]
When running PLN LDA when the grouping variable (here `Group`) has only two levels (TRUE,FALSE), the visualisation of the correlation circle is not implemented yet and raise the following error:

```
Error in combn(axes, 2, simplify = FALSE) : n < m
```

Here is a MWE:
```
library(ade4)
data("trichometeo")
trichometeo$meteo$Group <- trichometeo$meteo$Precip.Tot > 0

X<-as.matrix(trichometeo$fau)
G<-as.factor(trichometeo$meteo$Group)
library(PLNmodels)
LDA<-PLNLDA(X,G)
LDA$plot_LDA()
```

**Comment by cpauvert** [comment]
Inspiration can be found in [MASS::lda.R](https://github.com/cran/MASS/blob/6c1baa399304dbe97ab7bc11f202352aac0cfbf3/R/lda.R#L315) with the `ldahist` function

**Comment by jchiquet** [comment]
The following code is now working

``` R
library(ade4)
data("trichometeo")
trichometeo$meteo$Group <- trichometeo$meteo$Precip.Tot > 0

X<-as.matrix(trichometeo$fau)
G<-as.factor(trichometeo$meteo$Group)
library(PLNmodels)
LDA <- PLNLDA(X,G)
LDA$plot_LDA()
```

the same for

``` R
LDA$plot_individual_map()
LDA$plot_correlation_circle()
```
PCA methods have also been modified to integrate this feature.
