### ISSUE TITLE
Message d'erreur lors d'une tentative d'installation sous Mac OS

### ISSUE THREAD

**Issue by maberland** [jchiquet/PLNmodels#12]
Infos sur la session : 
###
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6
###

devtools::install_github("jchiquet/PLNmodels")
Downloading GitHub repo jchiquet/PLNmodels@master
from URL https://api.github.com/repos/jchiquet/PLNmodels/zipball/master
Installing PLNmodels
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/rz/5x9sk5zn3x78vx78l4q8yk100000gn/T/RtmpxDaFGu/devtools9337ae5d612/jchiquet-PLNmodels-661d206'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘PLNmodels’ ...
Using NLOPT_LIBS=-L/usr/local/Cellar/nlopt/2.4.2_2/lib -lnlopt -lm
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘PLNmodels’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/PLNmodels’
Installation failed: Command failed (1)

**Comment by mahendra-mariadassou** [comment]
Working solution (after reading http://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x and related posts). 

**For R 3.4.x (tested on MacOSX 10.13.5 High Sierra)**
Download macOS R toolchain: https://github.com/coatless/r-macos-rtools/releases (latest release is 1.1.0)

**For R 3.5.x (untested)**
Download and install "Development Tools and Libraries for MacOS X" at https://cran.r-project.org/bin/macosx/tools/
- https://cran.r-project.org/bin/macosx/tools/clang-6.0.0.pkg
- https://cran.r-project.org/bin/macosx/tools/gfortran-6.1.pkg

Create or modify `~/.R/Makevars` to make it look like:
- if  `ccache` is not installed
```
F77 = /usr/local/bin/gfortran
FC = $F77
CXX =  /usr/local/clang6/bin/clang++  -Wall
LDFLAGS=-L/usr/local/clang6/lib
CC=  /usr/local/clang6/bin/clang
SHLIB_CXXLD=ccache /usr/local/clang6/bin/clang++
CXX11 =  /usr/local/clang6/bin/clang++
CXX98 =  /usr/local/clang6/bin/clang++
CXX14 =  /usr/local/clang6/bin/clang++
```
- if `ccache` is installed (available from https://ccache.samba.org/)
```
F77 = /usr/local/bin/gfortran
FC = $F77
CXX = ccache /usr/local/clang6/bin/clang++  -Wall
LDFLAGS=-L/usr/local/clang6/lib
CC= ccache /usr/local/clang6/bin/clang
SHLIB_CXXLD=ccache /usr/local/clang6/bin/clang++
CXX11 = ccache /usr/local/clang6/bin/clang++
```

**Comment by maberland** [comment]
**Solution tested for R 3.4.x: installation succeeded but with warnings.**

devtools::install_github("jchiquet/PLNmodels")
Downloading GitHub repo jchiquet/PLNmodels@master
from URL https://api.github.com/repos/jchiquet/PLNmodels/zipball/master
Installing PLNmodels
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/rz/5x9sk5zn3x78vx78l4q8yk100000gn/T/Rtmp0PU7vY/devtoolsa756c7d2046/jchiquet-PLNmodels-661d206' --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘PLNmodels’ ...
Using NLOPT_LIBS=-L/usr/local/Cellar/nlopt/2.4.2_2/lib -lnlopt -lm
** libs
/usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
/usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2 -c call_nlopt_PLN.cpp -o call_nlopt_PLN.o
In file included from call_nlopt_PLN.cpp:5:
./utils_optim.h:74:50: warning: field 'Theta' will be initialized after field 'Omega' [-Wreorder]
    ) : Y(responses), X(covariates), O(offsets), Theta(regression_parameters), Omega(covinv), log_det_Omega(log_det)
                                                 ^
**1 warning generated.**
/usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2 -c call_nlopt_PLNPCA.cpp -o call_nlopt_PLNPCA.o
In file included from call_nlopt_PLNPCA.cpp:5:
./utils_optim.h:74:50: warning: field 'Theta' will be initialized after field 'Omega' [-Wreorder]
    ) : Y(responses), X(covariates), O(offsets), Theta(regression_parameters), Omega(covinv), log_det_Omega(log_det)
                                                 ^
**1 warning generated.**
/usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2 -c call_nlopt_PLN_VE.cpp -o call_nlopt_PLN_VE.o
In file included from call_nlopt_PLN_VE.cpp:5:
./utils_optim.h:74:50: warning: field 'Theta' will be initialized after field 'Omega' [-Wreorder]
    ) : Y(responses), X(covariates), O(offsets), Theta(regression_parameters), Omega(covinv), log_det_Omega(log_det)
                                                 ^
call_nlopt_PLN_VE.cpp:12:45: warning: unused variable 'd' [-Wunused-variable]
  int n = dat->Y.n_rows, p = dat->Y.n_cols, d = dat->X.n_cols ;
                                            ^
**2 warnings generated.**
/usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2 -c call_nlopt_PLNnetwork.cpp -o call_nlopt_PLNnetwork.o
In file included from call_nlopt_PLNnetwork.cpp:5:
./utils_optim.h:74:50: warning: field 'Theta' will be initialized after field 'Omega' [-Wreorder]
    ) : Y(responses), X(covariates), O(offsets), Theta(regression_parameters), Omega(covinv), log_det_Omega(log_det)
                                                 ^
**1 warning generated.**
/usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2 -c utils_optim.cpp -o utils_optim.o
In file included from utils_optim.cpp:1:
./utils_optim.h:74:50: warning: field 'Theta' will be initialized after field 'Omega' [-Wreorder]
    ) : Y(responses), X(covariates), O(offsets), Theta(regression_parameters), Omega(covinv), log_det_Omega(log_det)
                                                 ^
**1 warning generated.**
/usr/local/clang4/bin/clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/clang4/lib -o PLNmodels.so RcppExports.o call_nlopt_PLN.o call_nlopt_PLNPCA.o call_nlopt_PLN_VE.o call_nlopt_PLNnetwork.o utils_optim.o -fopenmp -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -L/usr/local/Cellar/nlopt/2.4.2_2/lib -lnlopt -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/PLNmodels/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** DONE (PLNmodels)**

**Comment by mahendra-mariadassou** [comment]
Oui les warnings dépendent de la "rigueur" du compilateur C++ utilisé (ils n'apparaissent pas chez moi) mais n'affectent normalement pas le bon fonctionnement du programme. Je vais essayer de corriger.
