### ISSUE TITLE
improve doc/vignette on PCA

### ISSUE THREAD

**Issue by BenoitLondon** [jchiquet/PLNmodels#13]
I managed to run a PLNPCA on my data but I m lost at how to get the following elements:
rotation matrix?
covariates regressors coefficients values?
Principal components values?

my model is something like `PLNPCA(pois_matrix ~  log_exposure_time + numeric_covariate)`

**Comment by BenoitLondon** [comment]
Ah OK i managed to go a bit further and recover the coefficients for the covariates with getBestModel and then model_par

**Comment by BenoitLondon** [comment]
I was expecting a summary/coef method like for a glm model. Otherwise very interesting Package! Good job and thanks for sharing.

**Comment by mahendra-mariadassou** [comment]
Dear Benoit, 

Thanks for the suggestion (and the many other ones). The idea to offer S3 methods to have the objects behave like a GLM is a very nice one. We'll look into it as soon as we come back from holidays.

**Comment by mahendra-mariadassou** [comment]
We added methods (S3 or not) for the 

- coefficients `coef` (S3 method)
- rotation matrix `$rotation`
- principal component values (or scores) `$scores`

and updated the vignette accordingly.
