### ISSUE TITLE
Make the interface more GLM-like?

### ISSUE THREAD

**Issue by BenoitLondon** [jchiquet/PLNmodels#14]
Would be handy to be able to provide a formula and the data where to pick the terms so it could deal with interactions automatically. Currently I understand I need to pass df$covariate_1 etc in the call to PLN(PCA) Also if I want interactions I have to build the vector before hand which is quite cumbersome.

Ideally something like PLNPCA(formula = output ~ x1 + x2 * x3, data = df)

**Comment by jchiquet** [comment]
Very good point. I am starting to working on it and will let you know when it will be available.

**Comment by jchiquet** [comment]
We can close this issue once a summary method will be available for PLN-fit and children, which requires resolution of #10 and #36.
