### ISSUE TITLE
Add weights parameters

### ISSUE THREAD

**Issue by BenoitLondon** [jchiquet/PLNmodels#16]
I imagine it could be possible to weight each observation differently with a weight vector. 
An argument weights would be handy in the PLN(PCA) calls (like in glm basically)

**Comment by jchiquet** [comment]
Ok, it corresponds to an enhancement related to issue #14 : I will be working on this at the same time (basiccaly, make the model more "GLM-like" like in standard R with `(g)lm`.

**Comment by jchiquet** [comment]
I reopen just to have the satisfaction to say that I added some support for weights for PLN, PLNLDA, PLNPCA, PLNnetwork.

I did some routines test for PLN and PLNLDA but not for the PLNPCA or PLNnetwork.
