### ISSUE TITLE
Plot method for PLN network

### ISSUE THREAD

**Issue by jchiquet** [jchiquet/PLNmodels#2]
Salut Julien,

je continue mon exploration de PLNnetwork. J'ai l'impression qu'il y a une blague dans l'option la fonction plot() en présence de covariables. La figure en bas à gauche ne contient qu'une colonne alors qu'elle devrait en comprendre autant que de covariables.

**Comment by cpauvert** [comment]
Salut!,
Je peux également reproduire le bug avec l'example ci dessous

```
library(ade4)
data("trichometeo")
library(PLNmodels)
abd<-as.matrix(trichometeo$fau)
net<-PLNnetwork( abd ~ 1 + trichometeo$meteo$Vent + trichometeo$meteo$Humidite)
net.best<-net$getBestModel()
net.best$plot()
```

Même en ajoutant un offset artificiel...

```
set.seed(101)
offset.tricho<-rpois(n = nrow(abd), lambda = 2)
offset.tricho<-offset.tricho %*% t(rep(1,times= ncol(abd)))
net<-PLNnetwork(abd ~ 1 + offset(offset.tricho) +  trichometeo$meteo$Vent + trichometeo$meteo$Humidite  )
net.best<-net$getBestModel()
net.best$plot()
```

Ce qui est étonnant puisque sur d'autres données j'arrive à afficher les coefficients des deux covariables.

**Comment by jchiquet** [comment]
Hello,

En fait le graphe affiche bien tous les effets liés aux covariables, mais ceux qui sont proches de 0 sont blancs, donc on ne les voit pas.

J'ai rajouté une grille autour des coefficients pour que ça soit clair pour l'utilisateur.
