### ISSUE TITLE
Add dependencies that are not on CRAN?

### ISSUE THREAD

**Issue by mahendra-mariadassou** [jchiquet/PLNmodels#21]
`prepare_data_from_biom` and `prepare_data_from_phyloseq` depend respectively on `biomformat` and `phyloseq` which are not on the CRAN but on Bioconductor and we only use those packages to have access to extractor functions. Right now, I don't `importFrom` the extractors to limit the number of dependencies but this results in warnings when checking the package. 

Should we:
- add the bioconductor dependencies (knowing that `phyloseq` already depends on `biomformat`)
- or ditch the two functions and only mention them in some "import data" vignettte?

**Comment by jchiquet** [comment]
I added bioconductor dependencies and ensured that travis checks are working in since commit 2085c0236176866a612a4c9c76c593b698adc12c
