### ISSUE TITLE
Vignettes are not build nor downloaded with devtools::install_github

### ISSUE THREAD

**Issue by cpauvert** [jchiquet/PLNmodels#22]
Hi,

Installing the package from the Github repo with `devtools` (as recommended in the README) did not build the vignettes
```
devtools::install_github("jchiquet/PLNmodels", build_vignettes = TRUE)
```
The vignettes directory was not even downloaded from the Github repo by R. I tested a manual download of the archive and a local installation but it did not build the vignettes either.

However, the issue is solved (vignettes are properly built) when removing the default parameters of the `build_opts` options (as follows)
```
devtools::install_github("jchiquet/PLNmodels",build_opts = c("--no-resave-data"))
# instead of the following default 
# build_opts = c("--no-resave-data", "--no-manual",   "--no-build-vignettes")
```
Nonetheless, some dependencies from the vignettes (e.g. `GGally` or `tidyverse`) needed to be installed by the user.

Hope you wanted to know
Charlie

**Comment by jchiquet** [comment]
Thanks Charlie, 

It has been corrected in the last version (see the README file)
