### ISSUE TITLE
Can't extract the StARS probability for all edges 

### ISSUE THREAD

**Issue by cpauvert** [jchiquet/PLNmodels#27]
Once the stability selection has been ran, it would be convenient to extract the probabilities from StARS for any model selected (BIC, StARS etc..). However, the `stability_path` data frame contains numeric indexes for the nodes instead of the nodes labels.

I wrote few lines to extract such probabilities just to check if it was feasible:

**Data**

```
library(PLNmodels)
library(tidyverse)
data("mollusk")
mollusc <- prepare_data(mollusk$Abundance, mollusk$Covariate, offset = "TSS")
mollusc<- mollusc %>%
  mutate(site_new =
           fct_collapse(site,
                        Gravier = c("GGravier1", "GGravier2", "GGravier3"),
                        Negria = c("Negria1", "Negria2")
           )
  )

Nets<-PLNnetwork( Abundance ~ 0 + site_new + offset(log(Offset)),data=mollusc,
                  control_init = list(nPenalties = 40,min.ratio=1e-2))
net_BIC<-getBestModel(Nets, "BIC")
Nets$stability_selection()
```
or `Nets <- readRDS("Nets_debug_StARS.RDS")` using the RDS (and zipped) file attached.

**Issue**

```

addStARsProba<-function(PLNfamily,PLNnet,debug=FALSE){
  # Check if stability was performed
  if (anyNA(PLNfamily$stability)) stop("stability selection has not yet been performed! Use stability_selection()")
  # Get the node labels
  node.labels <- colnames(PLNnet$latent_network())
  # Fetch the stability_path table and construct a named list with 
  #  the edges identifiers as names and the StARS probability as values (for the given penalty)
  probs<-PLNfamily$stability_path %>%
    # had to round to the same digits otherwise no intersection
    filter(round(Penalty,6)==round(PLNnet$penalty,6)) %>% 
    # Create the edge sequence
    mutate(NamedEdge=paste(node.labels[as.numeric(Node1)],
                           node.labels[as.numeric(Node2)],sep="|")) %>%
    select(x = Prob, nm = NamedEdge) %>% pmap(set_names) %>% unlist # as named list
  # Get the igraph object
  g<-plot(PLNnet,plot=F,remove.isolated = F)
  # match the edge sequence and add the probabilities
  if(debug){
    list("E" = probs[igraph::as_ids(igraph::E(g))],
         "Probs"=probs) 
  } else{ probs[igraph::as_ids(igraph::E(g))]}
}

# Extract the probabilities
addStARsProba(Nets, net_BIC)
Bit|Vac Vac|Vea    <NA>    <NA> Ans|Anl Ans|An- Ans|Pio Anl|An- Anl|Pio Pic|Pis Pin|Cat Pim|Pi- Cam|Cat 
   0.80    0.65      NA      NA    0.80    1.00    0.35    0.60    0.40    0.60    0.70    0.80    0.95 
Euf|Vea 
   1.00 
```
Presence of some NAs, meaning some edges in the selected network are not in the stability selection.

```
> which(colnames(net_BIC$latent_network())=="Lit")
[1] 7
> which(colnames(net_BIC$latent_network())=="Pis")
[1] 25
> Nets$stability_path[Nets$stability_path$Edge=="7--25",]
[1] Edge    Penalty Prob    Node1   Node2  
<0 lignes> (ou 'row.names' de longueur nulle)
> Nets$stability_path[Nets$stability_path$Edge=="25--7",]
[1] Edge    Penalty Prob    Node1   Node2  
<0 lignes> (ou 'row.names' de longueur nulle)
```

So the numerical indexes of the nodes in the StARS data frame would not be in the same order as the initial table?

I thought about tweaking the bit of code [there](https://github.com/jchiquet/PLNmodels/blob/754de929dacf2d12c41e496a82a3f21024f3c1a2/R/PLNnetworkfamily-class.R#L150) but it seems to depends on the `edge_to_node` which I was not sure what it was doing.

Thanks for considering this issue,
Charlie

[Nets_debug_StARS.zip](https://github.com/jchiquet/PLNmodels/files/2864036/Nets_debug_StARS.zip)

**Comment by mahendra-mariadassou** [comment]
Found it! This is a stupid bug that stems from the [portion](https://github.com/jchiquet/PLNmodels/blob/754de929dacf2d12c41e496a82a3f21024f3c1a2/R/PLNnetworkfamily-class.R#L152-156) where node numeric indexes are transformed to character before filtering on `Node1 < Node2` (which is actually unnecessary). This removes valid pairs as `2 < 10` but `"10" < "2"`. 

Fixing it.

**Comment by cpauvert** [comment]
Cool. Thanks!

**Comment by mahendra-mariadassou** [comment]
Do you think an `extract_probs` that takes a penalty (or criteria name such as "BIC", "EBIC" or "stars") and return the adjacency matrix with edges weighted by their inclusion frequency useful (or overkill)? 
This is essentially extraction and refactoring of `stability_path` and should not be too hard.

**Comment by cpauvert** [comment]
Yes, it could be perfect. You refer to the inclusion frequency as the `Probability` column in `stability_path` ?

The igraph object could then be constructed by hand with this matrix, or merged with another one as an edge attribute. The latter is perhaps too specific and could only  be written as an example (Not run) of `plot_network` to reduce the number of options.

**Comment by mahendra-mariadassou** [comment]
Yes, inclusion frequency refers to the `Probability` column. Writing the function is quite easy but I'm not very familiar with igraph syntax. If you have an example for the (not run), it would help a lot.

**Comment by cpauvert** [comment]
Sure, I can provide that.

**Comment by cpauvert** [comment]
I wrote an example given the same list of `PLNnetworkfit` called `Nets` above, but I can wrote a lighter one with `trichoptera` perhaps (you tell me):

```

# m <- Nets$extract_probs(): not available right now so improvising below
#  by creating a random matrix of probabilities
m <- as.matrix(net_BIC$latent_network())
m[upper.tri(m)]<-m[lower.tri(m)]<-runif(sum(lower.tri(m))) # The matrix is symetric 

# Get the network inferred by PLN into an igraph object
g <- plot(net_BIC, type = "partial_cor", plot=F)
g

# Several attributes but not the edge probability

IGRAPH cb6e511 UNW- 32 14 -- 
+ attr: name (v/c), label (v/c), label.cex (v/n), size (v/n), label.color (v/c), frame.color
| (v/l), weight (e/n), color (e/c), width (e/n)
+ edges from cb6e511 (vertex names):
 [1] Bit--Vac Vac--Vea Lit--Pis Pha--Hic Ans--Anl Ans--An- Ans--Pio Anl--An- Anl--Pio Pic--Pis Pin--Cat
[12] Pim--Pi- Cam--Cat Euf--Vea

# Construct a vector of edge probability from the m matrix
library(tidyverse)
probs <- m %>% reshape2::melt() %>% mutate( Edge_ID = paste(Var1,Var2,sep="|")) %>%
  select(x = value, nm = Edge_ID) %>% pmap(set_names) %>% unlist 

  Bit|Bit   Vap|Bit   Vac|Bit   Gac|Bit   Raa|Bit   Rap|Bit 
1.0000000 0.8255751 0.7065434 0.6223772 0.6693490 0.4842954 

# Create a new edge attribute and add to the graph
library(igraph)
E(g)$prob <- probs[ as_ids(E(g)) ]
g

IGRAPH cb6e511 UNW- 32 14 -- 
+ attr: name (v/c), label (v/c), label.cex (v/n), size (v/n), label.color (v/c), frame.color
| (v/l), weight (e/n), color (e/c), width (e/n), prob (e/n)
+ edges from cb6e511 (vertex names):
 [1] Bit--Vac Vac--Vea Lit--Pis Pha--Hic Ans--Anl Ans--An- Ans--Pio Anl--An- Anl--Pio Pic--Pis Pin--Cat
[12] Pim--Pi- Cam--Cat Euf--Vea
```

**Comment by mahendra-mariadassou** [comment]
No that's perfect. I'll make sure the function can produce either a matrix
or a named vector so that the bottom half of your example can be simplified
a bit.

Le jeu. 14 févr. 2019 à 18:16, Charlie Pauvert <notifications@github.com> a
écrit :

**Comment by mahendra-mariadassou** [comment]
`extracts_probs` should now work fine
