### ISSUE TITLE
Samples with NA in covariates are silently removed

### ISSUE THREAD

**Issue by cpauvert** [jchiquet/PLNmodels#29]
Hi again,

I just noticed that some samples were removed if `NA` were present in the covariates used (reprex below). Perhaps some users would like to know at least as a warning, like in the `prepare_data` function, before the #8 is solved, I guess. Otherwise, one can still check before including them.

```
data("trichoptera")
trichoptera <- prepare_data(trichoptera$Abundance, trichoptera$Covariate)
trichoptera$Pressure[29:32]<-NA
fit <- PLN(Abundance ~ 1 + Pressure + Temperature, data = trichoptera)

> dim(fitted(fit))
[1] 45 17
> dim(trichoptera$Abundance)
[1] 49 17

> data.frame(
+ fitted   = as.vector(fitted(fit)),
+ observed = as.vector(trichoptera$Abundance)
+ )
Error in data.frame(fitted = as.vector(fitted(fit)), observed = as.vector(trichoptera$Abundance)) : 
  les arguments impliquent des nombres de lignes différents : 765, 833
```

**Comment by mahendra-mariadassou** [comment]
This is the standard behavior for `lm` and `glm`. 

`
data("trichoptera")
trichoptera <- prepare_data(trichoptera$Abundance, trichoptera$Covariate)
trichoptera$Pressure[29:32]<-NA
fit <- lm(Precipitation ~ Pressure, data = trichoptera)

> length(fitted(fit))
[1] 45
> nrow(trichoptera)
[1] 49
`
@jchiquet may have a different opinion but I think we should stick with `lm` here. Issue #8 is slightly different: we can handle missing data in the *count* matrix, not in the covariates.

**Comment by cpauvert** [comment]
Alright
