### ISSUE TITLE
vcov is traditionally associated with the covariance of the coefficients, not with the residuals covariance

### ISSUE THREAD

**Issue by jchiquet** [jchiquet/PLNmodels#30]
- vcov should be used to access estimateor of the regression coefficients (also related to #10)
- to access the covariance of the residuals (aka Sigma), @mahendra-mariadassou  and I suggest to use 
   - coefficients(PLN, type = "covariance)
   - define a specific method. In LME4; "VarCorr" is used
   - overload vcov to add an argument (type = c("coefficients", "residuals")

**Comment by mahendra-mariadassou** [comment]
For `lm`, the standard way of extracting \(\Sigma\) is via `sigma` and there are some S3-methods for linear models (less than for `coef`) though. Maybe we can use `sigma.PLNfit` and overload `coefficients`.
