### ISSUE TITLE
Extend to distributions mix

### ISSUE THREAD

**Issue by BenoitLondon** [jchiquet/PLNmodels#39]
Was wondering if the algorithms here could be extended to a mix of count/binomial/continuous variables factors estimation in a unique algorithm. Say I have two Poisson and two Gaussian and 2 binomial variables?

**Comment by jchiquet** [comment]
Dear @BenoitLondon ,

FYI, our paper about probabilistic PCA (which PLNmodels is inspired from) describes how to deal with distributions from the  exponential family such as Bernoulli, Gaussian and Poisson. But not a mixture of them.

This is clearly out f the scope of the package:  we assume conditional Poisson distribution in all our model in this package. Maybe for further development, but we need some paper research first.

Thank you for you feedback anyway.
