### ISSUE TITLE
Problem when forcing the penalties in PLNnet

### ISSUE THREAD

**Issue by scj-robin** [jchiquet/PLNmodels#43]
I get an error when trying to fix the penalties for PLNnetwork, even when reusing the penalties provided by default:
------------------------------------------------------------------------------------------------------------------------
> PLNnet = PLNnetwork(Y ~ 1);
 Initialization...
 Adjusting 30 PLN with sparse inverse covariance estimation
	Joint optimization alternating gradient descent and graphical-lasso
	sparsifying penalty = 0.593625  
 Post-treatments
 DONE!
> lambda = PLNnet$penalties
> # lambda = exp(seq(1.5, -1.5, length.out=50))
> PLNnet = PLNnetwork(Y ~ 1, penalties=lambda)
 Initialization...
 Adjusting 30 PLN with sparse inverse covariance estimation
	Joint optimization alternating gradient descent and graphical-lasso
Error in if ((convergence[iter] < control$ftol_out
------------------------------------------------------------------------------------------------------------------------

**Comment by jchiquet** [comment]
Fixed since version 0.9.2-9001.
