### ISSUE TITLE
Adjustment of the penalty matrix to include prior independent features/species

### ISSUE THREAD

**Issue by cpauvert** [jchiquet/PLNmodels#44]
Hi!
The ranges of penalties (lambda) is currently uniform for the entire covariance matrix except the diagonal during the glasso step. Could it be possible to specify the penalties of some pairs of features (or species) within the `PLNnetwork` function ? 

Prior sparsity could then already be included if some pairs were not of interest. Such additional feature could be done by providing the indices of the entries to be set to zeroes just like in the the `glasso` package, and set such pairs to a high penalty (ex. lambda_[max] or a huge number).
However `glassoFast` only accepts penalty matrices so a post treatment of the generated matrix of penalty to set the pairs to high penalties. Such post treatment could happen there https://github.com/jchiquet/PLNmodels/blob/bf14cc032f0cd011fd1fd4afbb2e30cccc548abe/R/PLNnetworkfit-class.R#L76

Or the user could provide the entire matrix to `PLNnetwork` function, but it should be the list of matrices over the range of the suggested penalties and it seems a bit more difficult to include.

Thanks,
Charlie

**Comment by jchiquet** [comment]
Hi Charlie,

I am on it : We will keep an overall level of sparsity controlled by the `penalties`vector` along the regularization path, and add an optional matrix argument in the `control_main` list called penalty_weights to adapt the shrinkage according to our prior information. But this will remain the same all along the regularization path. Hope this fits to your needs.

J.

**Comment by jchiquet** [comment]
Hi Charlie,

The following piece of code should work in the since commit https://github.com/jchiquet/PLNmodels/commit/224b0853ad2c594c19651329bda05b15e4bf8761

```r 
library(PLNmodels)

data(trichoptera)
trichoptera <- prepare_data(trichoptera$Abundance, trichoptera$Covariate)

## some random weights
models_homegenous_penalties <- PLNnetwork(Abundance ~ 1, data = trichoptera)

## some random weights
p <- ncol(trichoptera$Abundance)
W <- diag(1, p, p)
W[upper.tri(W)] <- runif(p*(p-1)/2, min = 1, max = 5)
W[lower.tri(W)] <- t(W)[lower.tri(W)]

models_weighted_penalties <- 
  PLNnetwork(
    Abundance ~ 1,
    data = trichoptera,
    control_main = list(penalty_weights = W)
  )

plot(getBestModel(models_homegenous_penalties))

plot(getBestModel(models_weighted_penalties))
```

**Comment by cpauvert** [comment]
Hi Julien!
This is perfect! Thank you for the quick commit (as usual). The code snippet runs just fine.
C.

**Comment by scj-robin** [comment]
Do the model selection criteria need to be tuned, when few edges are penalized (all others being unpenalized i.e. having a weight close to zero).

For example,  seems that the binomial coefficient in the EBIC formula is not the right one as the number of possible models is smaller. Intuitively, choose(p(p-1)/2, E) should be replaced by choose(P, E_P), where
* P is the number of penalized edges
* E_P is the number of selected edges among the penalized ones.

**Comment by jchiquet** [comment]
answering @scj-robin 

A possible clue is to modify the degree of freedom (usually, number of activated variable), accouting for the weights in the penalty matrix.

This thing should have been studied probably when the adpative Lasso came out in the literature : how does its affect the (E)BIC, compared to the Lasso ?

Will check that later...
