### ISSUE TITLE
When preparing data from phyloseq, the abundance table has no rownames which breaks some plot functions 

### ISSUE THREAD

**Issue by jchiquet** [jchiquet/PLNmodels#45]
Basically, the object is converted to a matrix but it should have some rownames. Otherwise private$M does not have rownames and plot_indivudal_map breaks appart.

**Comment by mahendra-mariadassou** [comment]
I'll look into it but it's probably a problem on my side: phyloseq forces rownames for abundance tables.

**Comment by mahendra-mariadassou** [comment]
Do you have a MWE?

**Comment by jchiquet** [comment]
Unfortunately I cannot share the data with phyloseq format... (not published yet).

```
> head(rownames(PLNmodels::prepare_data_from_phyloseq(data)))
[1] "S.N.0115.1" "S.N.0116.1" "S.N.0116.2" "S.N.0116.4" "S.N.0116.5" "S.N.0116.6"
> rownames(PLNmodels::prepare_data_from_phyloseq(data)$Abundances)
```
If I add 

```
myData <- PLNmodels::prepare_data_from_phyloseq(data)
rownames(myData$Abundances) <- rownames(myData)
```

everything works fine then.

There is an (as, "matrix") in the prepare_data_phyloseq function and I dont know if it keep the rownames or what.

I can handle this latter anyway.

**Comment by mahendra-mariadassou** [comment]
I don't think it comes from the `as("matrix")` as its preserves rownames. And I'd be happy to investigate on a partial dataset as I can't reproduce the problem on the companion example [example_phyloseq.zip](https://github.com/jchiquet/PLNmodels/files/3373602/example_phyloseq.zip)

```
> library(PLNmodels)
> physeq <- readRDS("example_phyloseq.rds")
> myData <- PLNmodels::prepare_data_from_phyloseq(physeq)
> head(rownames(myData))
[1] "sa1" "sa2" "sa3" "sa4" "sa5" "sa6"
> head(rownames(myData$Abundance))
[1] "sa1" "sa2" "sa3" "sa4" "sa5" "sa6"
```

You can create a truncated version (2 samples, 2 OTUs, 2 covariates) of the phyloseq object with
```
n <- phyloseq::nsamples(data); p <- phyloseq::ntaxa(data) 
small_data <- phyloseq::prune_samples(rep(c(TRUE, FALSE), times = c(2, n - 2)), data)
small_data <-  phyloseq::prune_taxa(rep(c(TRUE, FALSE), times = c(2, p - 2)), small_data)
phyloseq::sample_data(small_data) <- phyloseq::sample_data(small_data)[, 1:2]
```

**Comment by jchiquet** [comment]
Ok, my mistake !!

The problem is due to data manipulation with tidytruc ! Try this :

```
physeq <- readRDS("example_phyloseq.rds")
myData <- PLNmodels::prepare_data_from_phyloseq(physeq)

head(rownames(myData))
head(rownames(myData$Abundance))

myData <- myData %>% mutate(Precipitation = 2 * Precipitation)

head(rownames(myData))
head(rownames(myData$Abundance))
```

Isn't it a bug from dplyr or something ?

**Comment by mahendra-mariadassou** [comment]
It's not really a bug, `dplyr` is quite opiniated on the fact that rownames are obsolete. dplyr verbs tend to remove rownames from data frames.

**Comment by EcoGinger** [comment]
![PLNmodels](https://user-images.githubusercontent.com/57043568/97624479-25fdbd00-19f5-11eb-8395-070e8753e678.png)
![error](https://user-images.githubusercontent.com/57043568/97624493-2ac27100-19f5-11eb-8f91-4919c5ae24a2.png)

Hi There! 

When I use the provided data and example I am not able to reproduce your results. Does prepare_data_from_phyloseq no longer work? 

Thanks for your help!

-Rachel
