### ISSUE TITLE
Error in common_samples(counts, covariates) : Incompatible dimensions

### ISSUE THREAD

**Issue by a-velt** [jchiquet/PLNmodels#46]
Hello Julien,
I tried to create the list input in order to use PLNmodels and I encountered some problems. 

I have two dataframes :

`head(Covariante)`

>   Prec0city Rep G L S M T MG B0u1dFree Year
> 1         1   1 1 1 0 1 1  1         0 2017
> 2         1   1 1 1 1 1 1  1         0 2017
> 3         1   1 1 1 1 1 0  1         0 2017
> 4         1   1 1 1 1 1 1  1         0 2017
> 5         1   1 1 1 1 0 1  1         0 2017
> 6         1   1 1 1 1 1 1  1         0 2017

`head(Abundance)`

> U1k10w1_75 U1k10w1_34 U1k10w1_27 U1k10w1_111 U1k10w1_100 U1k10w1_6 U1k10w1_56 U1k10w1_48 U1k10w1_60 U1k10w1_68
> 4023      21132          0       18661           0     97939      11972       7695       4804       5309
> 5544      15848          0       15970           0     86601      10622       7005       4112       4016
> 3692      18743          0       16992           0     83510      12104       6355       4135       5051
>   U1k10w1_69 U1k10w1_115 U1k10w1_31 U1k10w1_35 U1k10w1_49 U1k10w1_112 U1k10w1_130 U1k10w1_37 U1k10w1_32
> 9119       11325      82049      23164      10984       16138           0      20213      18832
> 7458           0      55167      20371      10559       13495           0      18999      20433
> 8679        9141      48772      22972      10898       14701       10551      19786      18824
> ...
> ...
> ...

I created a list of these dataframes : 
`liste=list(Abundance=Abundance, Covariante=Covariante)`

`str(liste, max.level = 1)`
> List of 2
>  $ Abundance :'data.frame':    444 obs. of  256 variables:
>  $ Covariante:'data.frame':    444 obs. of  10 variables:

`names(liste$Covariante)`
> [1] "Prec0city" "Rep"       "G"         "L"         "S"         "M"         "T"         "MG"        "B0u1dFree"
> [10] "Year"  

`names(liste$Abundance)`
 >  [1] "U1k10w1_75"  "U1k10w1_34"  "U1k10w1_27"  "U1k10w1_111" "U1k10w1_100" "U1k10w1_6"   "U1k10w1_56" 
>   [8] "U1k10w1_48"  "U1k10w1_60"  "U1k10w1_68"  "U1k10w1_69"  "U1k10w1_115" "U1k10w1_31"  "U1k10w1_35" 
>  [15] "U1k10w1_49"  "U1k10w1_112" "U1k10w1_130" "U1k10w1_37"  "U1k10w1_32"  
> ...
> ...

So I think here I have the good entries for the function prepare_data, so I tested : 

`data_prepare <- prepare_data(counts = liste$Abundance, covariates = liste$Covariate)`
> Error in common_samples(counts, covariates) : Incompatible dimensions
> In addition: Warning message:
> In common_samples(counts, covariates) :
>   There are no matching names in the count matrix and the covariates data.frame.
> Function will proceed assuming:
> - samples are in the same order;
> - samples are rows of the abundance matrix.

My samples are in the same order and samples are rows of the abundance matrix, so no problem with the warnings. But I don't understand the error : 

> Error in common_samples(counts, covariates) : Incompatible dimensions

I have the same number of rows, so what is the problem of incompatible dimensions ? 

Thank you for your help.
Best,
Amandine

**Comment by a-velt** [comment]
Julien, you can delete this issue, writing this post I realized that liste$Covariate is different from liste$Covariante :) I used the false term.
Thank you for this great tool,
Amandine

**Comment by jchiquet** [comment]
You known, @a-velt , I am relally enjoying this kind of Issue ;-)

**Comment by a-velt** [comment]
For sure ! :)
