### ISSUE TITLE
Installation fails on Windows 64 with gcc8 due to  DLL 'Rhdf5lib' not found

### ISSUE THREAD

**Issue by jchiquet** [jchiquet/PLNmodels#48]
CRAN asks to correct the following error before 2020-01-15 

https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64-gcc8/PLNmodels-00install.html

I suspect this is related to installation of BioConductor packages (phyloseq msot probably).

**Comment by mahendra-mariadassou** [comment]
OK I'll look into it

**Comment by jchiquet** [comment]
Any ideas @mahendra-mariadassou ? CRAN's ultimatum expires next Wednesday...

**Comment by mahendra-mariadassou** [comment]
J'ai bloqué demain après-midi pour regarder.

**Comment by mahendra-mariadassou** [comment]
It may harder than I thought. We depend on `phyloseq` (bioconductor) which imports `biomformat` (bioconductor) which imports `rhdf5` (bioconductor) which imports `rhdf5lib` (bioconductor). The last one provides hdf5 library as an R package. Everything works fine for r-devel (windows) but r-devel-gcc8 (for windows) uses an alternative toolchain based on gcc 8.0 from Rtools40. From the [website](https://github.com/r-windows/rtools-installer):

> The major difference between rtools and the upstream msys2 distribution is that our toolchains and external libraries have been reconfigured for static linking. This ensures that R packages built with rtools do not depend on any external dll files, and can be safely distributed as standalone binary packages.

This is more robust and likely to work nicely in the future but causes headaches for now as `rhdf5lib` relies on external dll file (the one not found: 
> DLL 'Rhdf5lib' not found: maybe not installed for this architecture?

I'm not sure there's an easy fix as the original package `rhdf5lib` needs to be adapted for static linking and use of the new toolchain. I'll let the package authors know about the problem (as they'll be concerned at some point). 

The only workaround I can think of is to remove the hard dependency to phyloseq and biomformat in the main code and tests and list them only as suggestions. If you're OK with that, I'll start the decoupling tomorrow afternoon.

**Comment by jchiquet** [comment]
Great that you clearly identified the while chain of the problem.

Maybe we can try to explain this to CRAN maintainers prior to removing phyloseq and biomat to PLNmodels ?

**Comment by mahendra-mariadassou** [comment]
If you think that will listen, we can try. On the meantime, I'll work on a
branch that requires no dependency (this kind of surprise is likely to
creep up again and the dependency on phyloseq is non essential)

**Comment by jchiquet** [comment]
Ok great ! And thanks.

**Comment by mahendra-mariadassou** [comment]
First try of bioc-free source package. Built for test with using r-devel-ATC on the [windows testing machine](https://win-builder.r-project.org/upload.aspx) of CRAN. 

[PLNmodels_0.9.3-9002.tar.gz](https://github.com/jchiquet/PLNmodels/files/4054177/PLNmodels_0.9.3-9002.tar.gz)

**Comment by jchiquet** [comment]
@mahendra-mariadassou you rock

**Comment by mahendra-mariadassou** [comment]
@jchiquet as the maintainer, you should receive an email in roughly 30 minutes with a link to the log file, according to [this page](https://win-builder.r-project.org/): 

> Wait for half an hour or so and check the e-mail address you have specified in the "Maintainer" field of the package's DESCRIPTION file. An e-mail should have arrived that will explain where the binary and the log files can be downloaded from: A randomly generated directory on this server which will be deleted after roughly 72 hours.

**Comment by jchiquet** [comment]
All checks and tests seem to pass.

Are we agree to merge to master?

**Comment by mahendra-mariadassou** [comment]
Go for it!

**Comment by jchiquet** [comment]
Hopefully fixed since v 0.9.4 and commit 5df4cac7fb08b687f1d59d0c396073fb20850d80

**Comment by mahendra-mariadassou** [comment]
For safekeeping and if we ever want to add back the dependencies: the problem has been solved by much smarter people (https://github.com/r-windows/checks/issues/43)
