### ISSUE TITLE
Add StARS selection criteria to PLN network

### ISSUE THREAD

**Issue by mahendra-mariadassou** [jchiquet/PLNmodels#5]
Add a stability selection step by default (with a limited number of resamples) and update getBestModel to output network with StARS selected lambda.

**Comment by jchiquet** [comment]
I started a [branch](https://github.com/jchiquet/PLNmodels/tree/StARS) to implementing feature

**Comment by jchiquet** [comment]
Done and inserted in the vignette of PLNnetwork. Here is a small example (note that the stability seleciton is performed only once)

``` R
library(PLNmodels)
library(ade4)
data("trichometeo")

abundance <- as.matrix(trichometeo$fau)

fits <- PLNnetwork(abundance)
network_StARS_.9  <- fits$getBestModel("StARS", stability = 0.9 )
network_StARS_.95 <- fits$getBestModel("StARS", stability = 0.95)
par(mfrow=c(1,2))
network_StARS_.9$plot_network()
network_StARS_.95$plot_network()
```
