### ISSUE TITLE
Plotting network with specific nodes 

### ISSUE THREAD

**Issue by erifa1** [jchiquet/PLNmodels#51]
Dear all, 

Which commands allows to plot only nodes having at least one edge in different networks?  as you do in figure 3 (http://proceedings.mlr.press/v97/chiquet19a/chiquet19a.pdf)

Thanks a lot,
Etienne

**Comment by jchiquet** [comment]
Suppose we infer a collection of networks just like in the example of the `PLNnetwork` function :
```
data(trichoptera)
trichoptera <- prepare_data(trichoptera$Abundance, trichoptera$Covariate)
fits <- PLNnetwork(Abundance ~ 1, data = trichoptera)
```

We can extract a specific network from this collection, e.g. with the BIC :

```
my_model <- getBestModel(fits, "BIC")
```

Then, an igraph object is recovered with plot.PLNnetwork S3 method :

```
my_graph <- plot(my_model, plot = FALSE)
my_graph
```

You then have an `igraph` object, for which an exhaustive documentation is available, e.g. [on the igraph documentation page for R](https://igraph.org/r/doc/)

In particular, using the plot.igraph function, you can specify whether or not you plot the isolated node like that :

```
plot(my_graph) # show isolated node
plot(delete.vertices(my_graph, v = which(degree(my_graph) == 0))) # remove isolated node
```

**Comment by erifa1** [comment]
It works well , thanks for your help!
