### ISSUE TITLE
Error in base::tcrossprod(x, y) : arguments inadéquats when attempting predict() 

### ISSUE THREAD

**Issue by vravigne** [jchiquet/PLNmodels#57]
We split our initial dataset into two datasets: one for training (80% samples) and one for prediction (20% samples). We then make PLN models on the training dataset and use the predict() function on the data to be predicted. The split is made at random. In some cases it works fine, but in other (too many) cases, we get an error from the predict() function : "Error in base::tcrossprod(x, y) : arguments inadéquats". Attached is an example of data and code with which we get the error. We also noticed that we get the error more often for the second model in the example (the one with factors) + this second model (with factors) has some warnings (Warning message:
glm.fit: fitted rates numerically 0 occurred)
Thanks for any clue/advice
[question_pour_Julien.zip](https://github.com/jchiquet/PLNmodels/files/4694963/question_pour_Julien.zip)

**Comment by mahendra-mariadassou** [comment]
The problem arises from predictor `annee`. You have years 1991 to 2009 but only 1992 to 2009, which leads to model matrices of different sizes. The base level is 1991 for the training set and 1992 for the prediction set. I thought that changing `annee` to a factor with fixed levels (1991 to 2009) would solve the problem but its doesn't. 

A quick and dirty fix would be to include one sample from 1991 to the prediction set. You can use that while I'm looking into a better solution. 

You shouldn't worry too much about the warning message for the second model. It arises from numerical problems when fitting GLM Poisson models that serve as a starting point for PLN models.

**Comment by vravigne** [comment]
Cristal clear ! Thanks Mahendra. We'll do test dirty fix tomorrow.
Best regards
Virginie

**Comment by mahendra-mariadassou** [comment]
I changed the code so that the predict() functions can handle factors with different levels in the training and prediction datasets (beware that some levels may not exist in the prediction dataset but that they should all be present in the training dataset). 

It still needs to be thoroughly tested but it should be included in the next release.

**Comment by vravigne** [comment]
That's quick ! We'll test this asap !

**Comment by jchiquet** [comment]
Hi @vravigne,

Before we merge the dev branch into the master, you will need to install the dev branch if you want to test Manhendra's update. You can do this with the following command line in R:

```
devtools::install_github('jchiquet/PLNmodels', ref='dev')
```

**Comment by vravigne** [comment]
Ok !

Le ven. 29 mai 2020 à 16:51, Julien Chiquet <notifications@github.com> a
écrit :
