### ISSUE TITLE
Document R6 classes in the spirit of the last version of Roxygen2

### ISSUE THREAD

**Issue by jchiquet** [jchiquet/PLNmodels#58]
Each method should be documented, close to the code.

Beware that the "set" method of R6 classes might poses a problem while documenting (the class should be defined once for all).

**Comment by mahendra-mariadassou** [comment]
See https://www.tidyverse.org/blog/2019/11/roxygen2-7-0-0/#r6-documentation for examples and references.

**Comment by mahendra-mariadassou** [comment]
Fixed in commit 66061d8dddfd5d77926fb65bda3f8d7d5dc0935f
