### ISSUE TITLE
Predictions for a model with no covariates

### ISSUE THREAD

**Issue by scj-robin** [jchiquet/PLNmodels#66]
No prediction seems to be reduced when including no covariate:
> library(PLNmodels);
> load('BarentsFish.Rdata')
> pln <- PLN(count ~ 1, data=Data)
> predict(pln, newdata=Data)
     Re_hi An_de An_mi Hi_pl An_lu Me_ae Ra_ra Mi_po Ar_at No_rk Lu_la Ma_vi Bo_sa Cy_lu Cl_ha Se_me Le_de Ga_mo
     Le_ma Se_ma Tr_es Ly_pa Ly_eu Ly_re Ly_se Ly_es Ly_va Be_gl Ca_re Tr_spp
attr(,"type")
[1] "link"

**Comment by mahendra-mariadassou** [comment]
I can't reproduce the problem with a different data set:
```
> library(PLNmodels)
> data(oaks)
> pln <- PLN(Abundance ~ 1, data = oaks)

 Initialization...
 Adjusting a PLN model with full covariance model
 Post-treatments...
 DONE!
> predict(pln, newdata = oaks)
```
works fine (with the latest CRAN version) and return a matrix of predicted counts. Can you attach `BarentsFish.data` to your issue so I can reproduce the problem?

**Comment by scj-robin** [comment]
[BarentsFish.Rdata.zip](https://github.com/jchiquet/PLNmodels/files/4965473/BarentsFish.Rdata.zip)
