### ISSUE TITLE
Find an example that works for GMPR normalizatino/offset

### ISSUE THREAD

**Issue by jchiquet** [jchiquet/PLNmodels#68]
Neither the trichoptera nor the oaks data set work : we get 

"Some sample(s) do not share any species with other samples, GMPR normalization failed."

(Infinite size factor)

For the moment, I commented the example in 'compute_offset' that would have caused an error in branch dev.

**Comment by EcoGinger** [comment]
Has this issue been solved? I'm still getting this error.

**Comment by mahendra-mariadassou** [comment]
It's been fixed in the latest version (0.10.6.9001). Which one are you using?

**Comment by EcoGinger** [comment]
When I use both install.packages("PLNmodels") and remotes::install_github("jchiquet/PLNmodels@0.10.6.9001") it says '0.10.6'.

**Comment by mahendra-mariadassou** [comment]
It should be enough. If you don't have problems with the following code (you shouldn't with version 0.10.6):
```
library(PLNmodels)
data(trichoptera)
counts <- trichoptera$Abundance
compute_offset(counts, offset = "GMPR")
```
you have the correct version of offset computations.
