### ISSUE TITLE
Does the method work for Poisson distributed data that's not an integer?

### ISSUE THREAD

**Issue by wrshoemaker** [jchiquet/PLNmodels#7]
Hello, I enjoyed reading your paper and would like to use your method. I have to duel boot my mac to run ubuntu before I can install and run your software though, so I wanted to ask my question before I try yo get your software running.

My data consists of Poisson distributed count data that has been divided by a constant to account for a covariate. Does your approach only work for integer count data? Or can it work with transformed count data that's no longer an integer.

Best,
Will

**Comment by mahendra-mariadassou** [comment]
Hello Will, 

There are two elements to the answer:
1/ the different methods used in the package assume count data but there is no strict enforcement of that and even quantities defined only on count data (like the factorial) are computed using continuous approximations for speed. Numerically, everything should work fine. 
2/ However, our preferred way to deal with covariate is no to divide the counts directly by the covariate but rather to include the covariate in the model, either as an offset (similar to exposure in Poisson regression, informally a coviariate with know regression coefficient equal 1) or as a genuine covariate (whose regression coefficient should be estimated). 

I hope it helps. 

Best
Mahendra

**Comment by jchiquet** [comment]
Hi,

+1 for Mahendra's answer.

For the record (I answered Will by email), the PLNPCA function runs even when the count table is not fill with integers, since it is treated in R as a numeric matrix (double or integer).

**Comment by wrshoemaker** [comment]
Thanks Mahendra and Julien,

Apologies for the delay, I was on vacation and am just now getting back into working with the package. I ran the `PLNnetwork()` function on the count table with non-discrete data. The function ran, but I got a list of long list of warnings, all of which were:

`Warning messages:
1: In dpois(y, mu, log = TRUE) : non-integer x = 1.644506`

And I'm not sure if the function converts that value into an integer or if it just skips it. I'm also working with fairly large matrices (115 x 356). The function takes a while to run, which is fine, but are there any issues with using `PLNnetwork()` on large networks besides runtime?

Again, thank you for your help.
Will

**Comment by wrshoemaker** [comment]
I forgot to include this in my previous comment. I wanted to ask about whether the size of the matrix could be a problem because there's this single large node in the network I get using the `plot_network()` that doesn't seem right.



<img width="273" alt="screen shot 2018-07-17 at 2 41 33 pm" src="https://user-images.githubusercontent.com/7355399/42838762-a765f5f0-89cf-11e8-85f7-9983e05ba7f8.png">
