### ISSUE TITLE
number of parameters in PLN 

### ISSUE THREAD

**Issue by wahid18benz** [jchiquet/PLNmodels#73]
Please does anyone know how nb_param is calculated in PLN ?

**Comment by jchiquet** [comment]
Yes, I do: this correspond to the number of parameters estimated in the current model, which depends on the number of covariates included, on the dimension of the count data (eg number of species), and the type of parametrization used for the variance-covariance matrix (full, diagonal, spherical, rank-constraints for PCA and sparsity constraints for PLNnetwork)

For instance in simple PLN, nb_param = number of mean parameters (number of entries in Theta) + number of variance-covariance parameters (Sigma, depending on the parameterization: full, diagonal, spherical). The same idea applies to PLNPCA (rank constraints), PLNnetwork (sparsity constraints)

Have a look at the vignettes to have a more comprehensive description of the different models, and thus more insight on the parametrization of the variance-covariance matrix Sigma and the regression parameters (or means) Theta.
