### ISSUE TITLE
Modify predict method for PLNPCA

### ISSUE THREAD

**Issue by mahendra-mariadassou** [jchiquet/PLNmodels#9]
Change predict method PLNPCA to easily handle new data by (i) estimating position in the latent space (without changing others parameters) and (ii) using those positions to predict class.

**Comment by mahendra-mariadassou** [comment]
First try at solving prediction problem, by creating a predict method for PLNfit. Estimating the position in the latent is a bit trickier as the mathematical procedure is not clear cut.

**Comment by jchiquet** [comment]
done via the predict method in PLNfit (common to PLNfit, PLNPCAfit and PLNnetworkfit). Distinct from the predict method of the supervised method PLNLDAfit.
